### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dhirk07** [h0nde/roblox-group-scanner#1]
When i run the script it says:

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 17, in worker_func
    os.sched_setaffinity(0, [cpu_num])
OSError: [Errno 22] Invalid argument
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 17, in worker_func
    os.sched_setaffinity(0, [cpu_num])
OSError: [Errno 22] Invalid argument
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 17, in worker_func
    os.sched_setaffinity(0, [cpu_num])
OSError: [Errno 22] Invalid argument
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 17, in worker_func
    os.sched_setaffinity(0, [cpu_num])
OSError: [Errno 22] Invalid argument
Process Process-15:
Process Process-5:
Process Process-8:
Process Process-6:
Process Process-3:
Process Process-4:
Process Process-12:
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Process Process-7:
Traceback (most recent call last):
Process Process-16:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
Process Process-14:
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
Process Process-13:
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
RuntimeError: can't start new thread
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
RuntimeError: can't start new thread
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/roblox-group-scanner/scanner/workers.py", line 40, in worker_func
    thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by Richodev** [comment]
suggest you to leave github,

**Comment by Richodev** [comment]
d

**Comment by Alektherblxdev** [comment]
Ay same, I'm running it on repl, wbu?

**Comment by NotSwaraj** [comment]
You guys are srsly clowns

**Comment by Richodev** [comment]
> You guys are srsly clowns
they should leave dev site.

**Comment by glixzzy** [comment]
I honestly don't know what's wrong, but for me, it works perfectly fine.... did you install all modules? if not do `pip install moduleNameHere` then run this in your terminal `python scanner --workers 16 --threads 500 --range 1-11000000` if you have **paid** proxies then run `python scanner --proxy-list proxies.txt --workers 16 --threads 500 --range 1-11000000` free proxies won't be as efficient, hope this helped cause it worked for me

**Comment by Squeakalus** [comment]
your running it on what i assume to be an absurd amount of threads, dont run this on 10000000 threads...

**Comment by Dhirk07** [comment]
> your running it on what i assume to be an absurd amount of threads, dont run this on 10000000 threads...

im running that on replit and also i didn't range that into 10m threads

**Comment by h0nde** [comment]
The `--workers`  argument tells python to start 16 sub-processes, with 500 threads running on each. Obviously, there's gonna be problems on weaker devices. I'd suggest lowering the worker and thread count.

**Comment by Dhirk07** [comment]
> The `--workers` argument tells python to start 16 subprocesses, with 500 threads running on each. Obviously, there's gonna be problems on weaker devices. I'd suggest lowering the worker and thread count.

Its working now but... it has 1 error only and that error says

 File "/home/runner/roblox-group-scanner/scanner/workers.py", line 19, in worker_func
    os.sched_setaffinity(0, [cpu_num])
OSError: [Errno 22] Invalid argument

**Comment by TheFarowHywolf** [comment]
> I honestly don't know what's wrong, but for me, it works perfectly fine.... did you install all modules? if not do `pip install moduleNameHere` then run this in your terminal `python scanner --workers 16 --threads 500 --range 1-11000000` if you have **paid** proxies then run `python scanner --proxy-list proxies.txt --workers 16 --threads 500 --range 1-11000000` free proxies won't be as efficient, hope this helped cause it worked for me

What Module?

**Comment by TheFarowHywolf** [comment]
How can i fix this `ModuleNotFoundError: No module named 'win32process'`

**Comment by h0nde** [comment]
Install the `pywin32` module. Run `pip install pywin32` in a command prompt window,

**Comment by glixzzy** [comment]
you guys should join the discord server, https://discord.gg/burgs, there is much better help there (instead of waiting hours for a response)
